#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "SauceCodePro Nerd Font:Bold:13.0"
spacebar -m config icon_font            "SauceCodePro Nerd Font:Regular:14.0"
spacebar -m config background_color     0x90202020
spacebar -m config foreground_color     0xffa8a8a8

spacebar -m config title                off

spacebar -m config spaces               on
spacebar -m config space_icon_strip     web term code 4 5 6 7 8 9 10
spacebar -m config space_icon           
spacebar -m config space_icon_color     0xffcd950c

spacebar -m config right_shell          off
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "echo $SHELL; echo [31ma"

spacebar -m config dnd                  on
spacebar -m config dnd_icon             
spacebar -m config dnd_icon_color       0xffa8a8a8

spacebar -m config power                on
spacebar -m config power_icon_strip     󰂄 
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f

spacebar -m config clock                on
spacebar -m config clock_icon           ""
spacebar -m config clock_format         "%Y-%m-%d (%A)   %R"
spacebar -m config clock_icon_color     0xffa8a8a8

echo "spacebar configuration loaded..."
