#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai -m config external_bar all:26:0
yabai -m config external_bar all:38:0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off

yabai -m config window_opacity               off
#yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8

yabai -m config window_border                off
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0xffa1c181
yabai -m config normal_window_border_color   0x001a1a1a
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
#yabai -m config layout                       bsp
yabai -m config layout                       float

yabai -m config top_padding                  0
# yabai -m config top_padding                  38
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   02

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Keychain Access$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^HandBrake$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^LINE$" manage=off
yabai -m rule --add app="^Alfred$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^alacritty$" manage=off
yabai -m rule --add app="^kitty$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off

yabai -m rule --add app="kittylauncher" manage=off sticky=on layer=above border=off
yabai -m rule --add app="kitty" manage=off sticky=on layer=above border=off

yabai -m space 1 --label one

echo "yabai configuration loaded..."
